accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_page, name="login"),
    path("request-otp/", views.request_otp, name="request_otp"),
    path("verify-otp/", views.verify_otp, name="verify_otp"),
    path("logout/", views.logout_view, name="logout"),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('batch-add/', views.batch_add, name='cart_batch_add'),
    path('', views.cart_page, name='cart_page'),
    path('add/<int:variant_id>/', views.add_to_cart, name='cart_add'),
    path('update/<int:variant_id>/', views.update_item, name='cart_update'),
    path('remove/<int:variant_id>/', views.remove_item, name='cart_remove'),
    path('clear/', views.clear_cart, name='cart_clear'),
    path('api/coupons/for-cart/', views.coupons_for_cart, name='coupons_for_cart'),
    path('api/coupons/apply/', views.api_apply_coupon, name='api_apply_coupon'),
    path("checkout/", views.checkout_page, name="checkout"),
    path("api/pincode/", views.api_pincode, name="api_pincode"),
    path("checkout/step-2/", views.checkout_step2, name="checkout_step2"),
    path("checkout/success/", views.checkout_success, name="checkout_success"),
]

quesec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import index as sitemap_index, sitemap as sitemap_view
from siteconfig.sitemaps import SITEMAPS, HomeSitemap, ShopSitemap, CategorySitemap, ProductVariantSitemap

urlpatterns = [
    path("admin/", admin.site.urls),

    # robots.txt (text/plain)
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        name="robots_txt",
    ),

    # Sitemaps
    path(
        "sitemap.xml",
        sitemap_index,
        {"sitemaps": SITEMAPS, "sitemap_url_name": "sitemaps"},
        name="sitemap-index",
    ),
    # Child files (dynamic; 'section' must match keys in SITEMAPS)
    path(
        "sitemap-<section>.xml",
        sitemap_view,
        {"sitemaps": SITEMAPS},
        name="sitemaps",
    ),

    # home
    path("", views.home, name="home"),

    # siteconfig
    path("siteconfig/", include("siteconfig.urls")),

    # cart first, with a fixed prefix
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),

    # cartwatch
    path("cartwatch/", include("cartwatch.urls")),

    # accounts, with a fixed prefix
    path("accounts/", include("accounts.urls")),

    # orders, with a fixed prefix
    path("orders/", include("orders.urls", namespace="orders")),

    # pages
    path("page/", include(("pages.urls", "pages"), namespace="pages")),

    # then shop (jisme catch-all slugs honge)
    path("", include(("shop.urls", "shop"), namespace="shop")),
    
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Custom error handlers
handler404 = "quesec.views.custom_404"
handler500 = "quesec.views.custom_500"
handler403 = "quesec.views.custom_403"
handler400 = "quesec.views.custom_400"

templates/partials/footer.html
{% load static %}
{% load static social_icons %}

<footer id="footer" class="footer md-pb-70">
    <div class="footer-wrap">
        <div class="footer-body">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-12">
                        <div class="footer-infor">
                            <div class="footer-logo">
                                {% if branding.logo %}
                                <a href="{{ branding.logo_link|default:'/' }}">
                                    <img src="{{ branding.logo.url }}" alt="Quesec Bikes">
                                </a>
                                {% endif %}
                            </div>
                            <ul>
                                <li>
                                    <p>Address: {{ contact_block.address_html|safe }}</p>
                                </li>
                                <li>
                                    <p>Email: <a href="mailto:{{ contact_block.email }}">{{ contact_block.email }}</a></p>
                                </li>
                                <li>
                                    <p>Phone: <a href="tel:{{ contact_block.phone }}">{{ contact_block.phone }}</a></p>
                                </li>
                            </ul>
                            <a href="{{ contact_block.map_link }}" class="tf-btn btn-line" target="_blank" rel="noopener">Get direction<i
                                    class="icon icon-arrow1-top-left"></i></a>
                            <ul class="tf-social-icon d-flex gap-10">
                                {% for s in social_links %}
                                <li>
                                    <a href="{{ s.url }}" target="_blank" rel="noopener"
                                        class="box-icon w_28 round social-{{ s.network }} bg_line">
                                        <i class="icon fs-12 {{ s.network|icon_for }}"></i>
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    {% for sec in footer_sections %}
                        {% if sec.title in "Shop Policies" %}
                            <div class="col-xl-3 col-md-6 col-12 footer-col-block">
                                <div class="footer-heading footer-heading-desktop">
                                    <h6>{{ sec.title }}</h6>
                                </div>
                                <div class="footer-heading footer-heading-moblie">
                                    <h6>{{ sec.title }}</h6>
                                </div>
                                <ul class="footer-menu-list tf-collapse-content">
                                    {% for link in sec.links.all %}
                                        {% if link.is_active %}
                                            <li>
                                                <a href="{{ link.url }}" class="footer-menu_item" {% if link.new_tab %} target="_blank" rel="noopener"{% endif %}>{{ link.label }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <div class="col-xl-3 col-md-6 col-12">
                        <div class="footer-newsletter footer-col-block">
                            <div class="footer-heading footer-heading-desktop">
                                <h6>Sign Up for Email</h6>
                            </div>
                            <div class="footer-heading footer-heading-moblie">
                                <h6>Sign Up for Email</h6>
                            </div>
                            <div class="tf-collapse-content">
                                <div class="footer-menu_item">Sign up to get first dibs on new arrivals, sales,
                                    exclusive content, events and more!</div>
                                <form class="form-newsletter subscribe-form" method="post" action="{% url 'newsletter_signup' %}">
                                    {% csrf_token %}
                                    <div class="subscribe-content">
                                        <fieldset class="email">
                                            <input type="email" name="email" class="subscribe-email"
                                                placeholder="Enter your email...." tabindex="0" aria-required="true" required>
                                        </fieldset>
                                        <div class="button-submit">
                                            <button 
                                                class="subscribe-button tf-btn btn-sm radius-3 btn-fill btn-icon animate-hover-btn"
                                                type="submit">Subscribe<i
                                                    class="icon icon-arrow1-top-left"></i></button>
                                        </div>
                                    </div>
                                    <div class="subscribe-msg"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div
                            class="footer-bottom-wrap d-flex gap-20 flex-wrap justify-content-between align-items-center">
                            <div class="footer-menu_item">© 2025 Quesec Bikes. All Rights Reserved</div>
                            <div class="tf-payment">
                                <img src="https://quesec-bikes-media.s3.ap-south-1.amazonaws.com/site/phonepay.png" alt="">
                                <img src="https://quesec-bikes-media.s3.ap-south-1.amazonaws.com/site/gpay.png" alt="">
                                <img src="https://quesec-bikes-media.s3.ap-south-1.amazonaws.com/site/paytm.png" alt="">
                                <img src="https://quesec-bikes-media.s3.ap-south-1.amazonaws.com/site/visa.png" alt="">
                                <img src="https://quesec-bikes-media.s3.ap-south-1.amazonaws.com/site/img-2.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/partials/head_seo.html
{# templates/partials/head_seo.html #}
{% with seo_index=seo.index|default:0 seo_canonical=seo.canonical|default:request.build_absolute_uri %}

  {% if seo_index %}
    <meta name="robots" content="index,follow"/>
  {% else %}
    <meta name="robots" content="noindex,nofollow"/>
  {% endif %}

    <link rel="canonical" href="{{ seo_canonical }}"/>

    <meta property="og:url" content="{{ seo_canonical }}"/>
    <meta property="og:type" content="{{ seo.og_type|default:'website' }}"/>
{% endwith %}

templates/partials/header.html
{% load static %}

<div class="px_15 lg-px_40">
    <div class="row wrapper-header align-items-center">
        <div class="col-md-4 col-3 tf-lg-hidden">
            <a href="index.html#mobileMenu" data-bs-toggle="offcanvas" aria-controls="offcanvasLeft">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="16" viewBox="0 0 24 16" fill="none">
                    <path
                        d="M2.00056 2.28571H16.8577C17.1608 2.28571 17.4515 2.16531 17.6658 1.95098C17.8802 1.73665 18.0006 1.44596 18.0006 1.14286C18.0006 0.839753 17.8802 0.549063 17.6658 0.334735C17.4515 0.120408 17.1608 0 16.8577 0H2.00056C1.69745 0 1.40676 0.120408 1.19244 0.334735C0.978109 0.549063 0.857702 0.839753 0.857702 1.14286C0.857702 1.44596 0.978109 1.73665 1.19244 1.95098C1.40676 2.16531 1.69745 2.28571 2.00056 2.28571ZM0.857702 8C0.857702 7.6969 0.978109 7.40621 1.19244 7.19188C1.40676 6.97755 1.69745 6.85714 2.00056 6.85714H22.572C22.8751 6.85714 23.1658 6.97755 23.3801 7.19188C23.5944 7.40621 23.7148 7.6969 23.7148 8C23.7148 8.30311 23.5944 8.59379 23.3801 8.80812C23.1658 9.02245 22.8751 9.14286 22.572 9.14286H2.00056C1.69745 9.14286 1.40676 9.02245 1.19244 8.80812C0.978109 8.59379 0.857702 8.30311 0.857702 8ZM0.857702 14.8571C0.857702 14.554 0.978109 14.2633 1.19244 14.049C1.40676 13.8347 1.69745 13.7143 2.00056 13.7143H12.2863C12.5894 13.7143 12.8801 13.8347 13.0944 14.049C13.3087 14.2633 13.4291 14.554 13.4291 14.8571C13.4291 15.1602 13.3087 15.4509 13.0944 15.6653C12.8801 15.8796 12.5894 16 12.2863 16H2.00056C1.69745 16 1.40676 15.8796 1.19244 15.6653C0.978109 15.4509 0.857702 15.1602 0.857702 14.8571Z"
                        fill="currentColor"></path>
                </svg>
            </a>
        </div>
        <div class="col-xl-3 col-md-4 col-6">
            {% if branding.logo %}
            <a href="{{ branding.logo_link|default:'/' }}" class="logo-header">
                <img src="{{ branding.logo.url }}" alt="Quesec Bikes" class="logo">
            </a>
            {% endif %}
        </div>
        <div class="col-xl-6 tf-md-hidden">
            <nav class="box-navigation text-center">
                <ul class="box-nav-ul d-flex align-items-center justify-content-center gap-30">
                    {% for item in primary_menu %}
                    <li class="menu-item"><a href="{{ item.url }}" class="item-link" {% if item.new_tab %} target="_blank" rel="noopener"{% endif %}>{{ item.label }}</a></li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
        <div class="col-xl-3 col-md-4 col-3">
            <ul class="nav-icon d-flex justify-content-end align-items-center gap-20">
                <li class="nav-search"><a href="index.html#canvasSearch" data-bs-toggle="offcanvas"
                        aria-controls="offcanvasLeft" class="nav-icon-item"><i class="icon icon-search"></i></a>
                </li>
                <li class="nav-account"><a href="{% if request.user.is_authenticated %}#{% else %}{% url 'accounts:login' %}{% endif %}" class="nav-icon-item"><i
                            class="icon icon-account"></i></a></li>
                <li class="nav-cart"><a href="{% url 'cart:cart_page' %}" class="nav-icon-item"><i
                            class="icon icon-bag"></i><span class="count-box">{{ cart_item_count|default:0 }}</span></a></li>
            </ul>
        </div>
    </div>
</div>

templates/partials/mobile-bottombar.html
<div class="tf-toolbar-bottom type-1150">
    <div class="toolbar-item">
        <a href="/">
            <div class="toolbar-icon">
                <i class="icon-home"></i>
            </div>
            <div class="toolbar-label">Home</div>
        </a>
    </div>
    <div class="toolbar-item">
        <a href="#canvasSearch" data-bs-toggle="offcanvas" aria-controls="offcanvasLeft">
            <div class="toolbar-icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-search"
                    viewBox="0 0 20 20">
                    <path
                        d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
                </svg>
            </div>
            <div class="toolbar-label">Search</div>
        </a>
    </div>
    <div class="toolbar-item">
        <a href="index.html#toolbarShopmb" data-bs-toggle="offcanvas" aria-controls="offcanvasLeft">
            <div class="toolbar-icon">
                <i class="icon-shop"></i>
            </div>
            <div class="toolbar-label">Shop</div>
        </a>
    </div>
    <div class="toolbar-item">
        <a href="index.html#login">
            <div class="toolbar-icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                    class="bi bi-whatsapp" viewBox="0 0 20 20">
                    <path
                        d="M13.601 2.326A7.85 7.85 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.9 7.9 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.9 7.9 0 0 0 13.6 2.326zM7.994 14.521a6.6 6.6 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.56 6.56 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592m3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.73.73 0 0 0-.529.247c-.182.198-.691.677-.691 1.654s.71 1.916.81 2.049c.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232" />
                </svg>
            </div>
            <div class="toolbar-label">Whatsapp</div>
        </a>
    </div>
    <div class="toolbar-item">
        <a href="https://amzn.to/47667KG">
            <div class="toolbar-icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-amazon"
                    viewBox="0 0 20 20">
                    <path
                        d="M10.813 11.968c.157.083.36.074.5-.05l.005.005a90 90 0 0 1 1.623-1.405c.173-.143.143-.372.006-.563l-.125-.17c-.345-.465-.673-.906-.673-1.791v-3.3l.001-.335c.008-1.265.014-2.421-.933-3.305C10.404.274 9.06 0 8.03 0 6.017 0 3.77.75 3.296 3.24c-.047.264.143.404.316.443l2.054.22c.19-.009.33-.196.366-.387.176-.857.896-1.271 1.703-1.271.435 0 .929.16 1.188.55.264.39.26.91.257 1.376v.432q-.3.033-.621.065c-1.113.114-2.397.246-3.36.67C3.873 5.91 2.94 7.08 2.94 8.798c0 2.2 1.387 3.298 3.168 3.298 1.506 0 2.328-.354 3.489-1.54l.167.246c.274.405.456.675 1.047 1.166ZM6.03 8.431C6.03 6.627 7.647 6.3 9.177 6.3v.57c.001.776.002 1.434-.396 2.133-.336.595-.87.961-1.465.961-.812 0-1.286-.619-1.286-1.533M.435 12.174c2.629 1.603 6.698 4.084 13.183.997.28-.116.475.078.199.431C13.538 13.96 11.312 16 7.57 16 3.832 16 .968 13.446.094 12.386c-.24-.275.036-.4.199-.299z" />
                    <path
                        d="M13.828 11.943c.567-.07 1.468-.027 1.645.204.135.176-.004.966-.233 1.533-.23.563-.572.961-.762 1.115s-.333.094-.23-.137c.105-.23.684-1.663.455-1.963-.213-.278-1.177-.177-1.625-.13l-.09.009q-.142.013-.233.024c-.193.021-.245.027-.274-.032-.074-.209.779-.556 1.347-.623" />
                </svg>
            </div>
            <div class="toolbar-label">Amazon</div>
        </a>
    </div>
</div>

templates/partials/mobile-header.html
{% load static %}

<div class="offcanvas offcanvas-start canvas-mb" id="mobileMenu">
    <span class="icon-close icon-close-popup" data-bs-dismiss="offcanvas" aria-label="Close"></span>
    <div class="mb-canvas-content">
        <div class="mb-body">
            <ul class="nav-ul-mb" id="wrapper-menu-navigation">
                {% for item in primary_menu %}
                <li class="nav-mb-item">
                    <a href="{{ item.url }}"
                        class="mb-menu-link" {% if item.new_tab %} target="_blank" rel="noopener"{% endif %}>{{ item.label }}</a>
                </li>
                {% endfor %}
            </ul>
            <div class="mb-other-content">
                <div class="d-flex group-icon">
                    <a href="{% if request.user.is_authenticated %}#{% else %}{% url 'accounts:login' %}{% endif %}" class="site-nav-icon"><i class="icon icon-account"></i>{% if request.user.is_authenticated %}My account{% else %}Login{% endif %}</a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/partials/topbar.html
{% load static %}
{% load static social_icons %}
<!-- Top Bar -->
<div class="tf-top-bar bg_white line">
    <div class="px_15 lg-px_40">
        <div class="tf-top-bar_wrap grid-3 gap-30 align-items-center">
            <ul class="tf-top-bar_item tf-social-icon d-flex gap-10">
                {% for s in social_links %}
                <li>
                    <a href="{{ s.url }}" target="_blank" rel="noopener"
                        class="box-icon w_28 round social-{{ s.network }} bg_line">
                        <i class="icon fs-12 {{ s.network|icon_for }}"></i>
                    </a>
                </li>
                {% endfor %}
            </ul>
            <div class="text-center overflow-hidden">
                <div dir="ltr" class="swiper tf-sw-top_bar" data-preview="1" data-space="0" data-loop="true"
                    data-speed="1000" data-delay="2000">
                    <div class="swiper-wrapper">
                        {% for m in topbar_messages %}
                        <div class="swiper-slide">
                            <p class="top-bar-text fw-5">{{ m.text }}</p>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Top Bar -->